# Generated by Django 6.0.3 on 2026-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('pol', models.CharField(choices=[('Men', 'Мальчик'), ('Women', 'Девочка')], verbose_name='Пол')),
                ('tip', models.CharField(choices=[('Dog', 'Собака'), ('Cat', 'Кошка')], verbose_name='Тип животного')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.CharField(verbose_name='Фото')),
            ],
        ),
    ]
