# Generated by Django 6.0.3 on 2026-04-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
    ]
