# Generated by Django 6.0.3 on 2026-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='На что были потрачены средства или что было собрано', verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма в рублях', max_digits=10, verbose_name='Сумма')),
                ('report_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Сбор')], default='expense', max_length=20, verbose_name='Тип отчета')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('receipt_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фото чека/документа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчетность',
                'ordering': ['-date'],
            },
        ),
    ]
